name: bookfoot237
description: Application de location de stades pour Yaoundé, Cameroun.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.1.1

  # Network & API  
  dio: ^5.3.2

  # Utilities
  intl: ^0.18.1

  #firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.6

  # Supabase pour le stockage des images
  supabase_flutter: ^2.5.6

  # Image picker pour sélectionner des images
  image_picker: ^1.0.7

  # Storage
  shared_preferences: ^2.5.3
  
  # Email service
  mailer: ^6.1.0
  
  # HTTP pour services externes
  http: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Quality
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true